### ISSUE TITLE
Support HDFS via hdfs-native package

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [delta-incubator/delta-kernel-rs#266]
delta-rs recently got initial support for hdfs via [this PR](https://github.com/delta-io/delta-rs/pull/2612).

It would be great if we could do the same for delta-rs-kernel. 

Duckdb recently introduced support for delta via kernel implementation but it can't be used with hdfs because of this missing integration.

Tagging @kimahriman to see if they can help out here!

**Comment by nicklan** [comment]
Yeah, seems like we could add this since https://github.com/datafusion-contrib/hdfs-native-object-store just makes hdfs look like an `object_store`, thanks!

Not sure when I will have time to work on this, but if someone wants to make a PR I'd be open to it, and I will find time at some point.

**Comment by SchutteJan** [comment]
@nicklan I would be interested in contributing to this, but I am completely new to this project.

Let me know if my understanding of the problem is correct, as I see it there are two ways to go about it:

- Add hdfs support into the upstream [object_store](https://docs.rs/object_store/latest/object_store/) crate, but looking at their issue (https://github.com/apache/arrow-rs/issues/5638) they seem to prefer to keep hdfs separate.

- Allow the current implementation to create object stores from `object_store` or `hdfs_native_object_store` crates
  - Similar to the implementation in `delta-rs`, you would match protocol schemes to the correct object store initializers
  - I.e.: `hdfs://` -> `hdfs_native_object_store::HdfsObjectStore` and `s3://` -> `object_store::ObjectStore`

**Comment by santosh-d3vpl3x** [comment]
2nd way would be the most straightforward and preferable I believe.

**Comment by Kimahriman** [comment]
Sorry GitHub randomly decided to stop sending me email notifications. `delta-rs` just uses a `dyn ObjectStore` so it was fairly easy to integrate. Haven't looked much at this repo yet to see how it handles object store but hopefully is straightforward!

**Comment by SchutteJan** [comment]
@nicklan I've marked my PR as ready, can you take a look?
